apiVersion: v1
kind: Pod
metadata:
  name: master-cassandra
  labels:
    name: master-cassandra
spec:
  containers:
    - image: bitnami/cassandra
      name: cassandra
      volumeMounts:
        - name: cassandra-data-master
          mountPath: /var/lib/cassandra
      env:
        - name: CASSANDRA_CLUSTER_NAME
          value: "kobito-db"
        - name: CASSANDRA_ENDPOINT_SNITCH
          value: "GoogleCloudSnitch"
        - name: CASSANDRA_PASSWORD_SEEDER
          value: "yes"
        - name: CASSANDRA_USER
          value: "kobito-cassandra"
        - name: CASSANDRA_PASSWORD
          value: "kobito-cassandra"
  volumes:
    - name: cassandra-data-master
      persistentVolumeClaim:
        claimName: cassandra-data-master
---
# Request a persistent volume from the cluster using a Persistent Volume Claim.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cassandra-data-master
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 50Gi